[ADD][8.0] l10n_id_taxform_period
OCA/l10n-indonesia pull request #10
Opened 2016-09-28 07:31 UTC by andhit-r

**Please give review on #9 since this PR is a part of module set that can only be reviewed if installed together**

================================
Indonesia's Taxform - Tax Period
================================

This module add feature to manage Indonesia's taxform period, both
tax year (tahun pajak) and tax period (massa pajak).

This module will be used by other taxform module.

Usage
=====

To manage taxform period you need to:

1. Go to menu *Taxform -> Configuration -> Period -> Tax Year*
2. Create, edit, or delete tax year data

2016-10-26 01:12 UTC, andhit-r commented
Hi @mikevhe18, @raditv, @azmimr67, @primeforcindo would you kindly review this PR. Many thanks

2016-10-28 10:49 UTC, mikevhe18 requested changes

2016-10-28 10:49 UTC, mikevhe18 commented on l10n_id_taxform_period/README.rst
> +<https://github.com/OCA//issues>`_. In case of trouble, please
https://github.com/OCA/l10n-indonesia/issues

2016-11-01 03:05 UTC, azmimr67 commented
Tested functionally on runboard 👍

2016-11-01 03:54 UTC, andhit-r commented
@mikevhe18 i addressed your comment on my last commit. Would you knindly review it it again.

2016-11-02 07:18 UTC, mikevhe18 commented
:+1: Tested on runbot

2016-12-21 11:36 UTC, merged

2016-12-21 13:05 UTC, raditv commented
Finally 👍